general:
  batch_size: 4
  device: cpu
  mode: train
  epoch: 2
  # cross = dual
  model_type: "cross"
  valid_size: 0.05
  test_size: 0.1
  max_length: 384
  n_worker: 2
  save_ckpt_per_n_epoch: 1 
  logging_per_steps: 100
  evaluate_per_step: 10000
  # envibert
  plm: xlmr
  accumulation_steps: 8

path: 
  pretrained_dir: pretrained
  train_data: data/ir/test
  test_data: data/ir/test
  warm_up: checkpoints/cross_1.bin
  ckpt: outputs/checkpoints
  log: outputs/logs
  bm25: outputs/bm25
  embedd_model: outputs/checkpoints/dual_0.bin

data_augmentation_args:
  augmentation_percent: 0.6
  mask_percent: 0.05
